---
title: "Feel the Vibes: AI-assisted Coding"
format:
  revealjs:
    theme: default
    slide-number: true
    toc: true
editor: visual
---

## Introduction and basics

Some things to mention here:

-   Brief explanation of LLMs
-   Distinction between models, reasoning models and agents
-   Why AI is so good at coding. Lot's of code online.
-   [Moore's law](https://theaidigest.org/time-horizons) for AI agents
-   Models, reasoning VS non-Reasoning and why the former is better at coding
-   Ways of interacting with the LLM
    -   Chatbot
    -   API
    -   IDE plugins
    -   Agents (automatically calls API with prompts)
-   Prompting: How to write a good prompt
    -   Role call: Rubber duck
    -   Say what style you want
        -   tidyverse, dplyr, R4DS, the package you use most
        -   Easy to read code (FAIR)
        -   No niche technologies and frameworks
        -   "Code that explains itself" -\> OSAH card
    -   Tell it all it needs to know
    -   Know what you want first, then ask
    -   What works best: ask for advice, not solutions
    -   (Optional:) If you do want a solution: Prompt engineering. Think of using GPS navigation
        -   Task = Your Target destination
        -   Context = Current location & conditions
        -   Reference = Route options available
        -   Evaluate = Examine best path forward
        -   Iterate = If needed, recalculate route
-   Typical tasks
-   I am using framework/package/context X. How do I do... (e.g. Jupyter notebook)
-   Research packages and frameworks that already do what you need (FAIR)
-   Refactoring
-   Generate synthetic data
-   Feedback (Context becomes super important here to not get lost on a tangent)

## Test GIF embedding

When we embed GIFs like this, it should be fine with GIPHY's [terms and conditions](https://support.giphy.com/hc/en-us/articles/360020027752-GIPHY-User-Terms-of-Service).

```{=html}
<iframe src="https://giphy.com/embed/YsTs5ltWtEhnq"
        width="480" height="270"
        style="display:block; margin:0 auto;"
        frameborder="0" allowfullscreen>
</iframe>
```

The embed button can be a bit hard to find. It is sometimes not displaying properly.

------------------------------------------------------------------------

## Slide 2

Here is another slide.
